<?php

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Tests\Etrias\EwarehousingConnector\Functional\Services;

use Etrias\EwarehousingConnector\Client\EwarehousingClient;
use Etrias\EwarehousingConnector\Client\EwarehousingClientInterface;
use Etrias\EwarehousingConnector\Response\GetContextResponse;
use Etrias\EwarehousingConnector\Services\AuthenticationService;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidFactory;

/**
 * @coversNothing
 */
class AuthenticationServiceTest extends BaseServiceTest
{
    /** @var AuthenticationService */
    protected $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $config = [
            'base_uri' => EwarehousingClientInterface::ENDPOINT_TEST,
        ];
        $client = new EwarehousingClient($config);
        $this->service = new AuthenticationService(
            $client,
            $this->serializer,
            getenv('USERNAME'),
            getenv('CUSTOMERID'),
            getenv('PASSWORD')
        );
    }

    public function testGetContext()
    {
        $response = $this->service->getContext();

        $this->assertInstanceOf(GetContextResponse::class, $response);
    }

    public function testGetHash()
    {
        $uuidFactory = new UuidFactory();
        $uuid = $uuidFactory->fromString($this->service->getHash());

        $this->assertInstanceOf(Uuid::class, $uuid);
    }
}
